### ISSUE TITLE
Some dumbass chat issue

### ISSUE THREAD

**Issue by ARandomGuy69** [CanyonNetwork/XOSurvival-Core#2]
Everytime I use a $ sign in chat it gives me this

```
[12:26:59 ERROR]: Could not pass event AsyncChatEvent to XOSurvivalCore v0.1
java.lang.IllegalArgumentException: Illegal group reference
        at java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1067) ~[?:?]
        at java.util.regex.Matcher.appendReplacement(Matcher.java:997) ~[?:?]
        at java.util.regex.Matcher.replaceAll(Matcher.java:1181) ~[?:?]
        at java.lang.String.replaceAll(String.java:2939) ~[?:?]
        at fwoostybots.com.xosurvivalcore.Events.ChatEvent.onChat(ChatEvent.java:62) ~[XOSurvivalCore-0.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor61.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-267]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:194) ~[paper-1.18.2.jar:git-Paper-267]
        at io.papermc.paper.adventure.ChatProcessor.processModern(ChatProcessor.java:105) ~[paper-1.18.2.jar:git-Paper-267]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:84) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2223) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2134) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2100) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket$1.run(ServerboundChatPacket.java:40) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by FroostySnoowman** [comment]
Fixed!
